version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres_django_orm_study
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - .volume/postgres:/var/lib/postgresql/data