# Generated by Django 4.0.2 on 2022-02-12 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=17, unique=True)),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('product_set_included_cart', models.ManyToManyField(related_name='carts_set', through='orm_study_app.Cart', to='orm_study_app.Product')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='related_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_study_app.seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_set_included_cart',
            field=models.ManyToManyField(related_name='carts_set', through='orm_study_app.Cart', to='orm_study_app.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='related_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_study_app.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_study_app.user'),
        ),
    ]
